name: 'Amplify PR Preview'
on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'Ready to merge')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: set branchname env
      id: setenvname
      run: |
        # use GITHUB_HEAD_REF that is set to PR source branch
        # also remove -_ from branch name and limit length to 10 for amplify env restriction
        echo "##[set-output name=setbranchname;]$(echo ${GITHUB_HEAD_REF//[-_]/} | cut -c-10)"

    - name: deploy PR preview
      uses: yinlinchen/amplify-preview-actions@0.2
      with:
        branch_name: ${{ steps.setenvname.outputs.setbranchname }}
        amplify_command: delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AmplifyAppId: ${{ secrets.AmplifyAppId }}
        BackendEnvARN: ${{ secrets.BackendEnvARN }}
        AWS_REGION: 'us-east-1'
